### PR TITLE
Make VirtualizedScrollPane's layoutChildren() method more developer-f…

### PR DESCRIPTION
**Pull request by JordanMartinez**
…riendly for those who want to extend the object.

### CODE REVIEW

**Comment by TomasMikula** [comment]
So what do you have in your overridden method then?

**Comment by JordanMartinez** [comment]
I have grown used to not using the area's normal `scaleY` value because the `pivotX` and `pivotY` aren't 0, 0. So, I added my own `Scale` object to the area's transformations. I also extend StyledTextArea and added some things to it. So, I wrote the code as (first is Groovy and then Java equivalent):
````groovy
// content has a Scale object called "s":
//    Scale s = new Scale(1, 1, 0, 0)
//    content.getTransforms().add(s)
content.with {
    resize(w, h / s.y)
}
````

````java
content.resize(w, h / content.scale.y);
````

**Comment by JordanMartinez** [comment]
If I only clip the content, then another issue arises: when zoomed in, then the area doesn't continue to scroll horizontally when typing beyond the width of the viewport because the clip's width (and thus the visually displayed width) is smaller than the viewport's width.

**Comment by TomasMikula** [comment]
While this change seems harmless, I'm not sure it's the best way to deal with the use-case you have.

What about implementing a `ScaledVirtualized` that wraps a `Virtualized` content and allows to set the scale. This `ScaledVirtualized` could then be put in `VirtualizedScrollPane`.

**Comment by JordanMartinez** [comment]
> While this change seems harmless, I'm not sure it's the best way to deal with the use-case you have.

Ok, but as a separate thought, wouldn't it still be useful to make `VirtualizedScrollPane` extendible?

> What about implementing a ScaledVirtualized that wraps a Virtualized content and allows to set the scale. 

So, something like this?
````java
public interface ScaledVirtualized extends Virtualized {
    public Scale scale = new Scale();
}
````

**Comment by TomasMikula** [comment]
I am not a big fan of the whole _customization by inheritance_ concept.

More like

```java
public class ScaledVirtualized<V extends Node & Virtualized> extends Region implements Virtualized {
    public ScaledVirtualized(V content) { ... }
    public ObjectProperty<Scale> scaleProperty();
}
```

**Comment by JordanMartinez** [comment]
> I am not a big fan of the whole _customization by inheritance_ concept.

Just personal preference? Or are there disadvantages to it?

> More like [example...]

Ah.... Ok, I see how that could work now.

**Comment by TomasMikula** [comment]
The principle is known as [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance#Benefits). In my experience, it leads to more modular and more readable code that is more robust with respect to future changes.

**Comment by TomasMikula** [comment]
If you are wondering, yes, we are violating this all over the place in ReactFX when we override `newObserver` or `observeInputs`. My reasoning was that it might be worth to save on the number of objects in such a basic thing as `EventStream` and `Val`, which are present in huge numbers in an application, but I didn't do any benchmarks.

**Comment by JordanMartinez** [comment]
> In my experience, it leads to more modular and more readable code that is more robust with respect to future changes.

The link was very helpful, thank you. I can see why one would do it that way.

> If you are wondering, yes, we are violating this all over the place in ReactFX

I hadn't thought about that, but I see that you're right. Breaking that principle here makes sense to me, but I guess doing a benchmark would be the only way to prove that.

Well, with that, I'm closing this PR.

**Pull request closed without merging**
