### PR TITLE
Made ScrollBars optional

### PR DESCRIPTION
**Pull request by JordanMartinez**
VirtualFlow is exposed and without visible scroll bars
VirtualizedScrollPane will add scroll bars on top of its content.

How's it look?

### CODE REVIEW

**Comment by JordanMartinez** [comment]
I just looked at the differences between the code and it looks terrible. Since VirtualFlowContent is renamed to VirtualFlow, it show all of VirtualFlow's class being deleted and VirtualFlowContent's content being written. If anyone looks back upon this change, it'll be really confusing as to what really changed.

**Comment by JordanMartinez** [comment]
Why did Travis CI fail? It said there was a problem with ":compileJava"

**Comment by TomasMikula** [comment]
Apparently, you didn't commit `Virtualized.java`.

**Comment by TomasMikula** [comment]
Yeah, it looks confusing. What about proceeding in two steps: keep the name `VirtualFlowContent` for now and the renaming can then be done in a separate commit.

**Comment by JordanMartinez** [comment]
Lol.............. Wow....... I guess I expected it would add it automatically.
If you look at [this branch](https://github.com/JordanMartinez/Flowless/tree/scrollBarsOptional), that's what I was going to do. Unfortunately, it didn't add Virtualized in that branch either. smh...

**Comment by JordanMartinez** [comment]
In that other branch, should the `dispose()` method be included?

**Comment by TomasMikula** [comment]
Hmm, `dispose()` in the current `VirtualFlow` only calls `content.dispose()`, which stops observing the list of items. That kind of dispose doesn't make sense for `VirtualizedScrollPane`. However there is a number of bindings created that are not disposed&mdash;they don't need to be disposed, because currently `VirtualFlow` and `VirtualFlowContent` always come together. However, if we allow to remove the `content` from `VirtualizedScrollPane`, we should dispose those bindings. Preferably, however, they should be disposed automatically when `content` is removed.

**Pull request closed without merging**
