### PR TITLE
Added option to change Scroll bars' policies; added corner

### PR DESCRIPTION
**Pull request by JordanMartinez**
With corner being added, I wasn't sure how to properly add the CSS file that would make its background color the same as the scrollbars background color. In RichTextFX, the color difference is still noticeable.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
When building via gradle, I also get theses warnings when it's running the `javadoc` task:
````
Flowless/src/main/java/org/fxmisc/flowless/VirtualizedScrollPane.java:33: 
    warning - Tag @see: can't find setHbarPolicy(ScrollBarPolicy) in org.fxmisc.flowless.VirtualizedScrollPane
Flowless/src/main/java/org/fxmisc/flowless/VirtualizedScrollPane.java:38: 
    warning - Tag @see: can't find setVbarPolicy(ScrollBarPolicy) in org.fxmisc.flowless.VirtualizedScrollPane
Flowless/src/main/java/org/fxmisc/flowless/VirtualizedScrollPane.java:33: 
    warning - Tag @see: can't find setHbarPolicy(ScrollBarPolicy) in org.fxmisc.flowless.VirtualizedScrollPane
Flowless/src/main/java/org/fxmisc/flowless/VirtualizedScrollPane.java:38: 
    warning - Tag @see: can't find setVbarPolicy(ScrollBarPolicy) in org.fxmisc.flowless.VirtualizedScrollPane
````

**Comment by TomasMikula** [comment]
Wouldn't just setting the background color of the whole `VirtualizedScrollPane` solve the same problem as adding a corner node with that background color?

**Comment by JordanMartinez** [comment]
....lol.... Yeah, actually. Why didn't I think of that?

**Comment by JordanMartinez** [comment]
I've opened up #22 so that the scroll bar policy excludes the corner commits.

**Pull request closed without merging**
